FROM node:20-alpine

RUN apk add --no-cache tzdata

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

ENV NODE_ENV=production
ENV TZ=Asia/Ho_Chi_Minh

CMD ["node", "worker.js"]